version: "3.9"
services:
  auth:
    build: auth-api/
    ports: 
      - "5000:5000"
    environment:
      FOO: bar

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: superpassword
  
  gameserver:
    build: game-server/
    ports:
      - "9999:9999"
